#ifndef APPDEFINES_H_RDLPTZCR
#define APPDEFINES_H_RDLPTZCR

#define SCREEN_SIZE 640, 480
#define VIEWPORT_DIMENSIONS 0, -80, 640, 640
#define VIEWPORT() glViewport( VIEWPORT_DIMENSIONS )
#define SPACELEAP_VIEWPORT

#define AQDOUBLE float
#define PPHYS_ALLOW_SLEEP 1

#endif /* end of include guard: APPDEFINES_H_RDLPTZCR */
